<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250728202834 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bank_account (id UUID NOT NULL, food_store_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, currency VARCHAR(3) DEFAULT \'CAD\' NOT NULL, account_holder_name VARCHAR(100) NOT NULL, transit_number VARCHAR(5) NOT NULL, institution_number VARCHAR(3) NOT NULL, account_number VARCHAR(12) NOT NULL, stripe_bank_token VARCHAR(50) DEFAULT NULL, last_four_digits VARCHAR(4) DEFAULT NULL, verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_default BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_53A23E0A98DF8F53 ON bank_account (food_store_id)');
        $this->addSql('COMMENT ON COLUMN bank_account.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN bank_account.food_store_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN bank_account.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bank_account.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN bank_account.verified_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE cart (id UUID NOT NULL, buyer_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, archived BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BA388B76C755722 ON cart (buyer_id)');
        $this->addSql('COMMENT ON COLUMN cart.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN cart.buyer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN cart.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cart.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE cart_dish (id UUID NOT NULL, cart_id UUID NOT NULL, dish_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, quantity INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7A988C811AD5CDBF ON cart_dish (cart_id)');
        $this->addSql('CREATE INDEX IDX_7A988C81148EB0CB ON cart_dish (dish_id)');
        $this->addSql('COMMENT ON COLUMN cart_dish.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN cart_dish.cart_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN cart_dish.dish_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN cart_dish.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cart_dish.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE cart_dish_ingredient (id UUID NOT NULL, cart_dish_id UUID NOT NULL, dish_ingredient_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, quantity INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E6FE6A6EF5478CC ON cart_dish_ingredient (cart_dish_id)');
        $this->addSql('CREATE INDEX IDX_E6FE6A6FE65422 ON cart_dish_ingredient (dish_ingredient_id)');
        $this->addSql('COMMENT ON COLUMN cart_dish_ingredient.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN cart_dish_ingredient.cart_dish_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN cart_dish_ingredient.dish_ingredient_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN cart_dish_ingredient.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN cart_dish_ingredient.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE categories (id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type VARCHAR(50) NOT NULL, name_fr VARCHAR(100) NOT NULL, name_en VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN categories.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN categories.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN categories.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE dish (id UUID NOT NULL, food_store_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, currency VARCHAR(3) NOT NULL, price NUMERIC(10, 2) NOT NULL, available BOOLEAN DEFAULT true NOT NULL, cached_average_rating DOUBLE PRECISION DEFAULT \'0\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_957D8CB898DF8F53 ON dish (food_store_id)');
        $this->addSql('COMMENT ON COLUMN dish.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dish.food_store_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dish.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN dish.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE dish_media (dish_id UUID NOT NULL, media_id UUID NOT NULL, PRIMARY KEY(dish_id, media_id))');
        $this->addSql('CREATE INDEX IDX_168341148EB0CB ON dish_media (dish_id)');
        $this->addSql('CREATE INDEX IDX_168341EA9FDD75 ON dish_media (media_id)');
        $this->addSql('COMMENT ON COLUMN dish_media.dish_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dish_media.media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE dish_categories (dish_id UUID NOT NULL, category_id UUID NOT NULL, PRIMARY KEY(dish_id, category_id))');
        $this->addSql('CREATE INDEX IDX_26455E4E148EB0CB ON dish_categories (dish_id)');
        $this->addSql('CREATE INDEX IDX_26455E4E12469DE2 ON dish_categories (category_id)');
        $this->addSql('COMMENT ON COLUMN dish_categories.dish_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dish_categories.category_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE dish_ingredient (id UUID NOT NULL, dish_id UUID DEFAULT NULL, ingredient_id UUID DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, currency VARCHAR(3) NOT NULL, price NUMERIC(10, 2) NOT NULL, available BOOLEAN DEFAULT true NOT NULL, is_supplement BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_77196056148EB0CB ON dish_ingredient (dish_id)');
        $this->addSql('CREATE INDEX IDX_77196056933FE08C ON dish_ingredient (ingredient_id)');
        $this->addSql('COMMENT ON COLUMN dish_ingredient.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dish_ingredient.dish_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dish_ingredient.ingredient_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dish_ingredient.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN dish_ingredient.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE dish_rating (id UUID NOT NULL, dish_id UUID NOT NULL, buyer_id UUID NOT NULL, order_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rating SMALLINT NOT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D08E212D148EB0CB ON dish_rating (dish_id)');
        $this->addSql('CREATE INDEX IDX_D08E212D6C755722 ON dish_rating (buyer_id)');
        $this->addSql('CREATE INDEX IDX_D08E212D8D9F6D38 ON dish_rating (order_id)');
        $this->addSql('COMMENT ON COLUMN dish_rating.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dish_rating.dish_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dish_rating.buyer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dish_rating.order_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN dish_rating.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN dish_rating.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE food_store (id UUID NOT NULL, seller_id UUID NOT NULL, profile_image_id UUID DEFAULT NULL, location_id UUID DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, stripe_account_id VARCHAR(255) DEFAULT NULL, stripe_onboarding_completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN NOT NULL, type VARCHAR(255) DEFAULT \'home\' NOT NULL, delivery_option VARCHAR(255) DEFAULT \'pickup_only\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E369D9D5E237E06 ON food_store (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E369D9D8DE820D9 ON food_store (seller_id)');
        $this->addSql('CREATE INDEX IDX_E369D9DC4CF44DC ON food_store (profile_image_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E369D9D64D218E ON food_store (location_id)');
        $this->addSql('COMMENT ON COLUMN food_store.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN food_store.seller_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN food_store.profile_image_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN food_store.location_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN food_store.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN food_store.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN food_store.stripe_onboarding_completed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE food_store_verification_request (id UUID NOT NULL, food_store_id UUID NOT NULL, verified_by_id UUID DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(255) DEFAULT \'pending\' NOT NULL, admin_comment TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C0EBE94798DF8F53 ON food_store_verification_request (food_store_id)');
        $this->addSql('CREATE INDEX IDX_C0EBE94769F4B775 ON food_store_verification_request (verified_by_id)');
        $this->addSql('COMMENT ON COLUMN food_store_verification_request.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN food_store_verification_request.food_store_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN food_store_verification_request.verified_by_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN food_store_verification_request.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN food_store_verification_request.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE verification_request_documents (request_id UUID NOT NULL, media_id UUID NOT NULL, PRIMARY KEY(request_id, media_id))');
        $this->addSql('CREATE INDEX IDX_F325269427EB8A5 ON verification_request_documents (request_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F325269EA9FDD75 ON verification_request_documents (media_id)');
        $this->addSql('COMMENT ON COLUMN verification_request_documents.request_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN verification_request_documents.media_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE ingredient (id UUID NOT NULL, food_store_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, name_fr VARCHAR(255) NOT NULL, name_en VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6BAF787098DF8F53 ON ingredient (food_store_id)');
        $this->addSql('COMMENT ON COLUMN ingredient.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN ingredient.food_store_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN ingredient.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN ingredient.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE location (id UUID NOT NULL, user_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, latitude DOUBLE PRECISION NOT NULL, longitude DOUBLE PRECISION NOT NULL, street VARCHAR(255) DEFAULT NULL, city VARCHAR(50) DEFAULT NULL, state VARCHAR(50) DEFAULT NULL, zip_code VARCHAR(10) DEFAULT NULL, country VARCHAR(100) DEFAULT NULL, additional_details VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E9E89CBA76ED395 ON location (user_id)');
        $this->addSql('COMMENT ON COLUMN location.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN location.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN location.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN location.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE media (id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, original_name VARCHAR(255) NOT NULL, file_name VARCHAR(255) NOT NULL, storage_path VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, file_type VARCHAR(50) NOT NULL, mime_type VARCHAR(100) NOT NULL, size INT NOT NULL, is_confidential BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A2CA10CD7DF1668 ON media (file_name)');
        $this->addSql('COMMENT ON COLUMN media.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN media.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN media.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE order_dish (id UUID NOT NULL, order_id UUID NOT NULL, cart_dish_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, currency VARCHAR(3) NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, base_subtotal_price NUMERIC(10, 2) NOT NULL, total_price NUMERIC(10, 2) NOT NULL, quantity INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D88CB6AF8D9F6D38 ON order_dish (order_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D88CB6AFEF5478CC ON order_dish (cart_dish_id)');
        $this->addSql('COMMENT ON COLUMN order_dish.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN order_dish.order_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN order_dish.cart_dish_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN order_dish.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN order_dish.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE order_dish_ingredient (id UUID NOT NULL, order_dish_id UUID NOT NULL, cart_dish_ingredient_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, currency VARCHAR(3) NOT NULL, price NUMERIC(10, 2) NOT NULL, quantity INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BC10A30AE2F41980 ON order_dish_ingredient (order_dish_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BC10A30A6E9DCC4F ON order_dish_ingredient (cart_dish_ingredient_id)');
        $this->addSql('COMMENT ON COLUMN order_dish_ingredient.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN order_dish_ingredient.order_dish_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN order_dish_ingredient.cart_dish_ingredient_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN order_dish_ingredient.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN order_dish_ingredient.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "orders" (id UUID NOT NULL, buyer_id UUID NOT NULL, cart_id UUID NOT NULL, food_store_id UUID NOT NULL, location_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, currency VARCHAR(3) NOT NULL, total_price NUMERIC(10, 2) NOT NULL, confirmation_code VARCHAR(6) NOT NULL, order_number VARCHAR(255) NOT NULL, status VARCHAR(255) DEFAULT \'pending\' NOT NULL, payment_status VARCHAR(255) DEFAULT \'pending\' NOT NULL, delivery_status VARCHAR(255) DEFAULT \'pending\' NOT NULL, buyer_note TEXT DEFAULT NULL, payment_method VARCHAR(255) DEFAULT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, paid_amount NUMERIC(10, 2) DEFAULT NULL, payment_currency VARCHAR(255) DEFAULT NULL, stripe_payment_intent_id VARCHAR(255) DEFAULT NULL, stripe_session_id VARCHAR(255) DEFAULT NULL, refunded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stripe_refund_id VARCHAR(255) DEFAULT NULL, delivery_method VARCHAR(255) DEFAULT \'pickup\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E52FFDEE551F0F81 ON "orders" (order_number)');
        $this->addSql('CREATE INDEX IDX_E52FFDEE6C755722 ON "orders" (buyer_id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEE1AD5CDBF ON "orders" (cart_id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEE98DF8F53 ON "orders" (food_store_id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEE64D218E ON "orders" (location_id)');
        $this->addSql('COMMENT ON COLUMN "orders".id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "orders".buyer_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "orders".cart_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "orders".food_store_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "orders".location_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN "orders".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "orders".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "orders".paid_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "orders".refunded_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE password_reset_token (id UUID NOT NULL, user_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, token VARCHAR(100) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6B7BA4B6A76ED395 ON password_reset_token (user_id)');
        $this->addSql('COMMENT ON COLUMN password_reset_token.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN password_reset_token.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN password_reset_token.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN password_reset_token.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN password_reset_token.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN password_reset_token.used_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE payout_configuration (id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, commission_rate NUMERIC(5, 2) NOT NULL, minimum_payout NUMERIC(10, 2) NOT NULL, maximum_payout NUMERIC(10, 2) NOT NULL, daily_limit NUMERIC(10, 2) NOT NULL, payout_cooldown_minutes INT NOT NULL, max_daily_payout_count INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN payout_configuration.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN payout_configuration.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN payout_configuration.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE refresh_token (id UUID NOT NULL, user_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, token VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74F21955F37A13B ON refresh_token (token)');
        $this->addSql('CREATE INDEX IDX_C74F2195A76ED395 ON refresh_token (user_id)');
        $this->addSql('COMMENT ON COLUMN refresh_token.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN refresh_token.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN refresh_token.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN refresh_token.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, default_address_id UUID DEFAULT NULL, profile_image_id UUID DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles JSON NOT NULL, is_active BOOLEAN NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, middle_name VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, type VARCHAR(50) DEFAULT NULL, phone_number VARCHAR(255) DEFAULT NULL, is_phone_confirmed BOOLEAN NOT NULL, phone_confirmation_token VARCHAR(255) DEFAULT NULL, phone_confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_email_confirmed BOOLEAN NOT NULL, email_confirmation_token VARCHAR(6) DEFAULT NULL, email_confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, email_confirmation_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, google_id VARCHAR(255) DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, locale VARCHAR(2) DEFAULT \'en\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE INDEX IDX_1483A5E9BD94FB16 ON users (default_address_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E9C4CF44DC ON users (profile_image_id)');
        $this->addSql('COMMENT ON COLUMN users.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN users.default_address_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN users.profile_image_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN users.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.phone_confirmed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.email_confirmed_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.email_confirmation_token_expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN users.deleted_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE wallet (id UUID NOT NULL, food_store_id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, currency VARCHAR(3) NOT NULL, available_balance NUMERIC(10, 2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7C68921F98DF8F53 ON wallet (food_store_id)');
        $this->addSql('COMMENT ON COLUMN wallet.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN wallet.food_store_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN wallet.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN wallet.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE wallet_transaction (id UUID NOT NULL, wallet_id UUID NOT NULL, order_id UUID DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, currency VARCHAR(3) NOT NULL, amount NUMERIC(10, 2) NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, stripe_payout_id VARCHAR(255) DEFAULT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, note TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7DAF972712520F3 ON wallet_transaction (wallet_id)');
        $this->addSql('CREATE INDEX IDX_7DAF9728D9F6D38 ON wallet_transaction (order_id)');
        $this->addSql('COMMENT ON COLUMN wallet_transaction.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN wallet_transaction.wallet_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN wallet_transaction.order_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN wallet_transaction.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN wallet_transaction.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN wallet_transaction.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE bank_account ADD CONSTRAINT FK_53A23E0A98DF8F53 FOREIGN KEY (food_store_id) REFERENCES food_store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B76C755722 FOREIGN KEY (buyer_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cart_dish ADD CONSTRAINT FK_7A988C811AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cart_dish ADD CONSTRAINT FK_7A988C81148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cart_dish_ingredient ADD CONSTRAINT FK_E6FE6A6EF5478CC FOREIGN KEY (cart_dish_id) REFERENCES cart_dish (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cart_dish_ingredient ADD CONSTRAINT FK_E6FE6A6FE65422 FOREIGN KEY (dish_ingredient_id) REFERENCES dish_ingredient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dish ADD CONSTRAINT FK_957D8CB898DF8F53 FOREIGN KEY (food_store_id) REFERENCES food_store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dish_media ADD CONSTRAINT FK_168341148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dish_media ADD CONSTRAINT FK_168341EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dish_categories ADD CONSTRAINT FK_26455E4E148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dish_categories ADD CONSTRAINT FK_26455E4E12469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dish_ingredient ADD CONSTRAINT FK_77196056148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dish_ingredient ADD CONSTRAINT FK_77196056933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dish_rating ADD CONSTRAINT FK_D08E212D148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dish_rating ADD CONSTRAINT FK_D08E212D6C755722 FOREIGN KEY (buyer_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dish_rating ADD CONSTRAINT FK_D08E212D8D9F6D38 FOREIGN KEY (order_id) REFERENCES "orders" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE food_store ADD CONSTRAINT FK_E369D9D8DE820D9 FOREIGN KEY (seller_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE food_store ADD CONSTRAINT FK_E369D9DC4CF44DC FOREIGN KEY (profile_image_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE food_store ADD CONSTRAINT FK_E369D9D64D218E FOREIGN KEY (location_id) REFERENCES location (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE food_store_verification_request ADD CONSTRAINT FK_C0EBE94798DF8F53 FOREIGN KEY (food_store_id) REFERENCES food_store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE food_store_verification_request ADD CONSTRAINT FK_C0EBE94769F4B775 FOREIGN KEY (verified_by_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE verification_request_documents ADD CONSTRAINT FK_F325269427EB8A5 FOREIGN KEY (request_id) REFERENCES food_store_verification_request (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE verification_request_documents ADD CONSTRAINT FK_F325269EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ingredient ADD CONSTRAINT FK_6BAF787098DF8F53 FOREIGN KEY (food_store_id) REFERENCES food_store (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CBA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_dish ADD CONSTRAINT FK_D88CB6AF8D9F6D38 FOREIGN KEY (order_id) REFERENCES "orders" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_dish ADD CONSTRAINT FK_D88CB6AFEF5478CC FOREIGN KEY (cart_dish_id) REFERENCES cart_dish (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_dish_ingredient ADD CONSTRAINT FK_BC10A30AE2F41980 FOREIGN KEY (order_dish_id) REFERENCES order_dish (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_dish_ingredient ADD CONSTRAINT FK_BC10A30A6E9DCC4F FOREIGN KEY (cart_dish_ingredient_id) REFERENCES cart_dish_ingredient (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "orders" ADD CONSTRAINT FK_E52FFDEE6C755722 FOREIGN KEY (buyer_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "orders" ADD CONSTRAINT FK_E52FFDEE1AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "orders" ADD CONSTRAINT FK_E52FFDEE98DF8F53 FOREIGN KEY (food_store_id) REFERENCES food_store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "orders" ADD CONSTRAINT FK_E52FFDEE64D218E FOREIGN KEY (location_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE password_reset_token ADD CONSTRAINT FK_6B7BA4B6A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE refresh_token ADD CONSTRAINT FK_C74F2195A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9BD94FB16 FOREIGN KEY (default_address_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9C4CF44DC FOREIGN KEY (profile_image_id) REFERENCES media (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT FK_7C68921F98DF8F53 FOREIGN KEY (food_store_id) REFERENCES food_store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE wallet_transaction ADD CONSTRAINT FK_7DAF972712520F3 FOREIGN KEY (wallet_id) REFERENCES wallet (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE wallet_transaction ADD CONSTRAINT FK_7DAF9728D9F6D38 FOREIGN KEY (order_id) REFERENCES "orders" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE bank_account DROP CONSTRAINT FK_53A23E0A98DF8F53');
        $this->addSql('ALTER TABLE cart DROP CONSTRAINT FK_BA388B76C755722');
        $this->addSql('ALTER TABLE cart_dish DROP CONSTRAINT FK_7A988C811AD5CDBF');
        $this->addSql('ALTER TABLE cart_dish DROP CONSTRAINT FK_7A988C81148EB0CB');
        $this->addSql('ALTER TABLE cart_dish_ingredient DROP CONSTRAINT FK_E6FE6A6EF5478CC');
        $this->addSql('ALTER TABLE cart_dish_ingredient DROP CONSTRAINT FK_E6FE6A6FE65422');
        $this->addSql('ALTER TABLE dish DROP CONSTRAINT FK_957D8CB898DF8F53');
        $this->addSql('ALTER TABLE dish_media DROP CONSTRAINT FK_168341148EB0CB');
        $this->addSql('ALTER TABLE dish_media DROP CONSTRAINT FK_168341EA9FDD75');
        $this->addSql('ALTER TABLE dish_categories DROP CONSTRAINT FK_26455E4E148EB0CB');
        $this->addSql('ALTER TABLE dish_categories DROP CONSTRAINT FK_26455E4E12469DE2');
        $this->addSql('ALTER TABLE dish_ingredient DROP CONSTRAINT FK_77196056148EB0CB');
        $this->addSql('ALTER TABLE dish_ingredient DROP CONSTRAINT FK_77196056933FE08C');
        $this->addSql('ALTER TABLE dish_rating DROP CONSTRAINT FK_D08E212D148EB0CB');
        $this->addSql('ALTER TABLE dish_rating DROP CONSTRAINT FK_D08E212D6C755722');
        $this->addSql('ALTER TABLE dish_rating DROP CONSTRAINT FK_D08E212D8D9F6D38');
        $this->addSql('ALTER TABLE food_store DROP CONSTRAINT FK_E369D9D8DE820D9');
        $this->addSql('ALTER TABLE food_store DROP CONSTRAINT FK_E369D9DC4CF44DC');
        $this->addSql('ALTER TABLE food_store DROP CONSTRAINT FK_E369D9D64D218E');
        $this->addSql('ALTER TABLE food_store_verification_request DROP CONSTRAINT FK_C0EBE94798DF8F53');
        $this->addSql('ALTER TABLE food_store_verification_request DROP CONSTRAINT FK_C0EBE94769F4B775');
        $this->addSql('ALTER TABLE verification_request_documents DROP CONSTRAINT FK_F325269427EB8A5');
        $this->addSql('ALTER TABLE verification_request_documents DROP CONSTRAINT FK_F325269EA9FDD75');
        $this->addSql('ALTER TABLE ingredient DROP CONSTRAINT FK_6BAF787098DF8F53');
        $this->addSql('ALTER TABLE location DROP CONSTRAINT FK_5E9E89CBA76ED395');
        $this->addSql('ALTER TABLE order_dish DROP CONSTRAINT FK_D88CB6AF8D9F6D38');
        $this->addSql('ALTER TABLE order_dish DROP CONSTRAINT FK_D88CB6AFEF5478CC');
        $this->addSql('ALTER TABLE order_dish_ingredient DROP CONSTRAINT FK_BC10A30AE2F41980');
        $this->addSql('ALTER TABLE order_dish_ingredient DROP CONSTRAINT FK_BC10A30A6E9DCC4F');
        $this->addSql('ALTER TABLE "orders" DROP CONSTRAINT FK_E52FFDEE6C755722');
        $this->addSql('ALTER TABLE "orders" DROP CONSTRAINT FK_E52FFDEE1AD5CDBF');
        $this->addSql('ALTER TABLE "orders" DROP CONSTRAINT FK_E52FFDEE98DF8F53');
        $this->addSql('ALTER TABLE "orders" DROP CONSTRAINT FK_E52FFDEE64D218E');
        $this->addSql('ALTER TABLE password_reset_token DROP CONSTRAINT FK_6B7BA4B6A76ED395');
        $this->addSql('ALTER TABLE refresh_token DROP CONSTRAINT FK_C74F2195A76ED395');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9BD94FB16');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9C4CF44DC');
        $this->addSql('ALTER TABLE wallet DROP CONSTRAINT FK_7C68921F98DF8F53');
        $this->addSql('ALTER TABLE wallet_transaction DROP CONSTRAINT FK_7DAF972712520F3');
        $this->addSql('ALTER TABLE wallet_transaction DROP CONSTRAINT FK_7DAF9728D9F6D38');
        $this->addSql('DROP TABLE bank_account');
        $this->addSql('DROP TABLE cart');
        $this->addSql('DROP TABLE cart_dish');
        $this->addSql('DROP TABLE cart_dish_ingredient');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE dish');
        $this->addSql('DROP TABLE dish_media');
        $this->addSql('DROP TABLE dish_categories');
        $this->addSql('DROP TABLE dish_ingredient');
        $this->addSql('DROP TABLE dish_rating');
        $this->addSql('DROP TABLE food_store');
        $this->addSql('DROP TABLE food_store_verification_request');
        $this->addSql('DROP TABLE verification_request_documents');
        $this->addSql('DROP TABLE ingredient');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE order_dish');
        $this->addSql('DROP TABLE order_dish_ingredient');
        $this->addSql('DROP TABLE "orders"');
        $this->addSql('DROP TABLE password_reset_token');
        $this->addSql('DROP TABLE payout_configuration');
        $this->addSql('DROP TABLE refresh_token');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE wallet');
        $this->addSql('DROP TABLE wallet_transaction');
    }
}
