// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR92FwUoNJ3TQf2DFne_JocX3ud0ibdDA',
    appId: '1:963257456085:web:3ff62274b519d5fb60595c',
    messagingSenderId: '963257456085',
    projectId: 'cuisinous-f3c9a',
    authDomain: 'cuisinous-f3c9a.firebaseapp.com',
    storageBucket: 'cuisinous-f3c9a.firebasestorage.app',
    measurementId: 'G-L9Z9FE1D1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwI9zZndqvjubI1OtkfNVDtBb6UdOKmRE',
    appId: '1:963257456085:android:4147bb866c2b847760595c',
    messagingSenderId: '963257456085',
    projectId: 'cuisinous-f3c9a',
    storageBucket: 'cuisinous-f3c9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8LrL-22N_P0sE-XPnqRxPrRuqy6HG6Hk',
    appId: '1:963257456085:ios:e7a3a44d12ca651b60595c',
    messagingSenderId: '963257456085',
    projectId: 'cuisinous-f3c9a',
    storageBucket: 'cuisinous-f3c9a.firebasestorage.app',
    iosBundleId: 'ca.cuisinous',
  );
}
